In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier

# Import metrics module for performance evaluation
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("../datasets/diabetes_dataset.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.to_csv("test.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
corr = df.corr()

In [ ]:
df['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [ ]:
X = df.drop(columns=['Outcome'])
y = df['Outcome']

In [ ]:
# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
# Create and train KNN classifier
k = 3
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

# Predict on test set
predictions = knn.predict(X_test)

In [ ]:
# Calculate model accuracy
print("Accuracy:",accuracy_score(y_test, predictions))
# Calculate model precision
print("Precision:",precision_score(y_test, predictions))
# Calculate model recall
print("Recall:",recall_score(y_test, predictions))
# Calculate model f1 score
print("F1-Score:",f1_score(y_test, predictions))

Accuracy: 0.6753246753246753
Precision: 0.5274725274725275
Recall: 0.6
F1-Score: 0.5614035087719298

### With own dataset

In [ ]:
df = pd.read_csv(r"..\datasets\students_data_set\Logistics Regreesion\framingham.csv")
df

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,1,50,1.0,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1
4234,1,51,3.0,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,0
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4238 non-null   int64
 1   age              4238 non-null   int64
 2   education        4133 non-null   float64
 3   currentSmoker    4238 non-null   int64
 4   cigsPerDay       4209 non-null   float64
 5   BPMeds           4185 non-null   float64
 6   prevalentStroke  4238 non-null   int64
 7   prevalentHyp     4238 non-null   int64
 8   diabetes         4238 non-null   int64
 9   totChol          4188 non-null   float64
 10  sysBP            4238 non-null   float64
 11  diaBP            4238 non-null   float64
 12  BMI              4219 non-null   float64
 13  heartRate        4237 non-null   float64
 14  glucose          3850 non-null   float64
 15  TenYearCHD       4238 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 529.9 KB

In [ ]:
df.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [ ]:
df2 = df.dropna()
df2.drop(columns=['male','education','currentSmoker','prevalentStroke','prevalentHyp','diabetes','age','BPMeds'],inplace=True)
df2

C:\Users\Admin\AppData\Local\Temp\ipykernel_9508\1720729910.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(columns=['male','education','currentSmoker','prevalentStroke','prevalentHyp','diabetes','age','BPMeds'],inplace=True)

      cigsPerDay  totChol  sysBP  diaBP    BMI  heartRate  glucose  TenYearCHD
0            0.0    195.0  106.0   70.0  26.97       80.0     77.0           0
1            0.0    250.0  121.0   81.0  28.73       95.0     76.0           0
2           20.0    245.0  127.5   80.0  25.34       75.0     70.0           0
3           30.0    225.0  150.0   95.0  28.58       65.0    103.0           1
4           23.0    285.0  130.0   84.0  23.10       85.0     85.0           0
...          ...      ...    ...    ...    ...        ...      ...         ...
4231         0.0    187.0  141.0   81.0  24.96       80.0     81.0           0
4232         0.0    176.0  168.0   97.0  23.14       60.0     79.0           1
4233         1.0    313.0  179.0   92.0  25.97       66.0     86.0           1
4234        43.0    207.0  126.5   80.0  19.71       65.0     68.0           0
4237         0.0    269.0  133.5   83.0  21.47       80.0    107.0           0

[3656 rows x 8 columns]

In [ ]:
df['BPMeds'].value_counts()

0.0    4061
1.0     124
Name: BPMeds, dtype: int64

In [ ]:
df2.shape

(3656, 8)

In [ ]:
df2.isnull().sum()

cigsPerDay    0
totChol       0
sysBP         0
diaBP         0
BMI           0
heartRate     0
glucose       0
TenYearCHD    0
dtype: int64

In [ ]:
df2["TenYearCHD"].value_counts()

0    3099
1     557
Name: TenYearCHD, dtype: int64

In [ ]:
df2.corr()

,cigsPerDay,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
cigsPerDay,1.000000,-0.030222,-0.094764,-0.056650,-0.086888,0.063549,-0.053803,0.052159
totChol,-0.030222,1.000000,0.220130,0.174986,0.120799,0.093057,0.049749,0.091127
sysBP,-0.094764,0.220130,1.000000,0.786727,0.331004,0.184901,0.134702,0.222885
diaBP,-0.056650,0.174986,0.786727,1.000000,0.385611,0.179008,0.063704,0.150342
BMI,-0.086888,0.120799,0.331004,0.385611,1.000000,0.074401,0.083671,0.081931
heartRate,0.063549,0.093057,0.184901,0.179008,0.074401,1.000000,0.097026,0.020523
glucose,-0.053803,0.049749,0.134702,0.063704,0.083671,0.097026,1.000000,0.121942
TenYearCHD,0.052159,0.091127,0.222885,0.150342,0.081931,0.020523,0.121942,1.000000

In [ ]:
x = df2.drop(columns=['TenYearCHD'])
y = df2["TenYearCHD"]

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.3)

In [ ]:
k = 5
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
pred = knn.predict(X_test)

In [ ]:
# Calculate model accuracy
print("Accuracy:",accuracy_score(y_test, pred))
# Calculate model precision
print("Precision:",precision_score(y_test, pred))
# Calculate model recall
print("Recall:",recall_score(y_test, pred))
# Calculate model f1 score
print("F1-Score:",f1_score(y_test, pred))

Accuracy: 0.8240656335460347
Precision: 0.3389830508474576
Recall: 0.11494252873563218
F1-Score: 0.17167381974248927