# **GIVEN DATASET**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("diabetes_dataset.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [ ]:
corr = df.corr()

In [ ]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
X = df.drop(columns=['Outcome'])
y = df['Outcome']

In [ ]:
# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
# Create and train KNN classifier
k = 3
model = KNeighborsClassifier(n_neighbors=k)
model.fit(X_train, y_train)
# Predict on test set
y_pred= model.predict(X_test)

In [ ]:
print("Accuracy:",accuracy_score(y_test, y_pred))
print("Precision:",precision_score(y_test, y_pred))
print("Recall:",recall_score(y_test, y_pred))
print("F1-Score:",f1_score(y_test, y_pred))

Accuracy: 0.6753246753246753
Precision: 0.5274725274725275
Recall: 0.6
F1-Score: 0.5614035087719298

# **OWN DATASET**

In [2]:
df = pd.read_csv("customer-decision tree.csv")
df.head()

   age  income  will_buy
0   25   30000         0
1   35   40000         1
2   45   60000         1
3   30   35000         0
4   50   80000         1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       96 non-null     int64
 1   income    96 non-null     int64
 2   will_buy  96 non-null     int64
dtypes: int64(3)
memory usage: 2.4 KB

In [4]:
corr = df.corr()

In [5]:
df['will_buy'].value_counts()

will_buy
1    67
0    29
Name: count, dtype: int64

In [7]:
X = df.drop(columns=['will_buy'])
y = df['will_buy']

In [8]:
# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [9]:
# Create and train KNN classifier
k = 3
model = KNeighborsClassifier(n_neighbors=k)
model.fit(X_train, y_train)
# Predict on test set
y_pred= model.predict(X_test)

In [10]:
print("Accuracy:",accuracy_score(y_test, y_pred))
print("Precision:",precision_score(y_test, y_pred))
print("Recall:",recall_score(y_test, y_pred))
print("F1-Score:",f1_score(y_test, y_pred))

Accuracy: 0.9655172413793104
Precision: 1.0
Recall: 0.9523809523809523
F1-Score: 0.975609756097561